name: harry_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  youtube_player_flutter: ^8.1.2
  # url_launcher: ^6.1.12
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:

  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600

